### ISSUE TITLE
How will the event system be designed?

### ISSUE THREAD

**Issue by Matt5sean3** [HackRVA/Badge2017-docs#2]
I'm adding this issue mainly to allow continued conversation on this topic and to document ideas that have been proposed so far. Seeing as the badge code is not yet available, there was a desire to create detailed pseudocode for this functionality and then propose from the pseudocode.

The consensus at the end of the previous meeting seemed to be that the event system would have separate lists for each event and that each program would use a 32-bit bitmask to determine which events it would handle. There was also mention of using an 8-bit unsigned integer to indicate which app is currently running.

An alternate idea was to use a singular list that all event handlers were attached to which passed all events through that list.

Use of multiple list was preferred as it was believed that the multiple lists would lead to cleaner app design and be more efficient in general.

One of the problems for the event system was how to register and deregister events from the event system such that once one app stops, the other. The favored solution for this problem escapes me at the moment, but if someone else remembers please detail it below.

I suggested that an app could provide a pointer to an array of event handler structs prefixed by the number of entries in that array to provide the means to register events for a particular app. Upon exit from the app, this pointer would be overwritten by the new app's pointer thereby making registration of the new app and deregistration of the old app essentially the same action.

There are a lot of other ideas and suggestions that did not stick in my brain so please add whichever ideas you suggest or remember.

**Comment by dotblank** [comment]
Perhaps something similar to this:

```
include event.h
/*
struct event_registration_t {EVENT_TYPE type; void* func_cb}
*/

struct event_registration_t handlers[] = {
   {EVENT_TYPE_BUTTON_RELEASED, app_handle_button_ev};
}
```

Its not actual c but it should get the idea across. There is a cost that the event system (want to call it dispatcher?) will have to walk down the array. It could be suggested that the frequent events should be earlier in the list

This removes the need for bit-mask but adds overhead that scales with the number of handlers. We can have a TON events but we do not care as long as not all apps handle all of them.

A:

```
EVENT_TYPE_BUTTON e;
e.action == BUTTON_RELEASED
```

vs.
B:
`EVENT_TYPE_BUTTON_RELEASED`

If the cost for new event types is low I suggest B otherwise I suggest A

Any thoughts on what would be best?

**Comment by jonathan46000** [comment]
```
XMaskEvent(KEY_EVENTS, *XEvent_t);//XEvent_t returns the XEvent Struct for that event type.
    if(XEvent_t.keyup) {
        if(XEvent_t.key == "SomeKey") {
            //Do Some Stuff
        }
    }
```

This is the X11 method of handling it which is similar to method A, currently we don't have the functionality on the badge necessary for this as we don't register events to this detail IE we don't detect whether an action is key-up or key-down(IR being its own animal).  That being said I think B is a better approach.

**Comment by Matt5sean3** [comment]
Using a bitmask or otherwise explicitly declaring which events are used, could the interrupts that generate unused events be turned off while that app is running? That would reduce the number of events that get handled in general and provide some better control to the app writers if they need it.

Separately, If method B is implemented such that the user provides an array of handlers and an array providing the index of the handler for the events used, the cost to add a new type of event could be a single byte up to 254 events. However, this method limits to a single handler per event.

Something like:

``` C
/* our code */
/* in .h */
typedef void (*evt_handler_t)();

enum evt_type_e {
  EVT_TYPE_TIMER1,
  EVT_TYPE_TIMER2,
  /* etc. */
  EVT_TYPE_BUTTON2,
  EVT_TYPE_NUM_TYPES
};

typedef struct evt_mapping_t {
  enum evt_type_e event;
  unsigned char index;
} evt_mapping_t;

void evt_dispatch(enum evt_type_e event_type);
void evt_register(const evt_handler_t* handlers, const evt_mapping_t* mapping, int mapping_size);
/* in .c */

/* I'm not 100% that treating the last entry in the enum as an int to get the number of events is wise */
/* Having these as global variable seems justified */
unsigned char evt_mapping[EVT_TYPE_NUM_TYPES];
const evt_handler_t* evt_handlers;

void evt_register(const evt_handler_t* handlers, const evt_mapping_t* mapping, int mapping_size) {
  unsigned char i;
  evt_handlers = handlers;
  /* More efficient clean-up methods than this are possible, I'm sure */
  for(i = 0; i < EVENT_TYPE_NUM_TYPES; i++) {
    evt_mapping[i] = 255;
  }
  for(i = 0; i < mapping_size; i++) {
    evt_mapping[mapping[i]->event] = mapping[i]->index;
  }
}

void evt_dispatch(enum evt_type_e event_type) {
  unsigned char handler_index = evt_mapping[event_type];
  if(handler_index < 255) {
    evt_handlers[handler_index]();
  }
}
```

**Comment by Matt5sean3** [comment]
As an aside, we might have been jumping to implementation ideas a bit too fast on this one.

What design goals do we have and which are most important?
- Does adding events piecemeal need to be possible or can we limit events to being set in batches?
- Do we want to have user data pointers or just have people use global variables?
- What should the maximum number of event handlers be?
- How many handlers should any single event should support?
- How much RAM and how much flash are we aiming to contain this system within?
- How quickly do events need to be processed?
- How easy does this need to be to interact with for the app developers?

Answer these and we can probably get a better sense of which solutions fit better.

**Comment by dotblank** [comment]
I can't answer all of these but I can put my thoughts on one
-     How many handlers should any single event should support?

I think it should be more than one.
eg:  EVT_TYPE_BUTTON_PRESS:

```
wakeup();
debug_hook() //optional
fun_stat_collector() //Achievement Unlocked!! I Pressed the button 400 times!
app_cb();

```

If we have only one handler per event it is more difficult to see where all the events end up going. If we can't have a friendly spot to place them they are going to put it wherever the event itself is dispatched or even worse in the ISR.

In practice i'd say 1-3 events for most and have a max of ~10

**Comment by dotblank** [comment]
> How easy does this need to be to interact with for the app developers?

It shouldn't be too onerous and if we make the function of it simple and limited in scope, the more likely the dev will use it.

**Comment by Matt5sean3** [comment]
I can agree with that well enough, ensure we have a max of at least a few.

Actually, I'll put my proposals for some of the questions:
- Allowing adding events piecemeal should not be made a priority.
- User data pointers should be supported
- support at least 100 handlers collectively
- A single event should be able to support at least 8 handlers
- I'll leave it to those with more experience on the platform to determine flash and RAM size limits
- Time to process handlers should kept low but isn't the top point in trade offs against RAM usage
- Requiring app developers to be really good about cleaning up after themselves if something like deregistration is necessary could cause some hard to debug problems down the road, so try to keep things more or less foolproof.

**Comment by dotblank** [comment]
Perhaps something similar to this:

include event.h
/*
struct event_registration_t {EVENT_TYPE type; void* func_cb}
*/

struct event_registration_t handlers[] = {
   {EVENT_TYPE_BUTTON_RELEASED, app_handle_button_ev};
}

Its not actual c but it should get the idea across. There is a cost that
the event system (want to call it dispatcher?) will have to walk down the
array. It could be suggested that the frequent events should be earlier in
the list

This removes the need for bit-mask but adds overhead that scales with the
number of handlers. We can have a TON events but we do not care as long as
not all apps handle all of them.


A:
EVENT_TYPE_BUTTON e;
event.action == BUTTON_RELEASED

vs.
B:
EVENT_TYPE_BUTTON_RELEASED

If the cost for new event types is low I suggest B otherwise I suggest A

Any thoughts on what would be best?

**Comment by jonathan46000** [comment]
Just cosigning what Eli said. Thats a super important part of it. 

Jonathan Lundquist

**Comment by jonathan46000** [comment]
So before we make too many recommendations lets look at the current code and determine exactly what events are being use, or were implemented and not used, and what those events are. I'll work on this tonight and put out a list of current events and categorize them used/not used.  

Jonathan Lundquist

**Comment by dotblank** [comment]
Here are some of the most common use of button events, sliders...

```
#define BUTTON_PRESSED ((sampleButtonStatus & BUTTON_MASK) && \
    (buttonTimestamp[BUTTON] != lastHandledTimestamp[BUTTON])

#define BUTTON_PRESSED_AND_CONSUME ((sampleButtonStatus & BUTTON_MASK) && \
    (buttonTimestamp[BUTTON] != lastHandledTimestamp[BUTTON]) && \
    (lastHandledTimestamp[BUTTON] = buttonTimestamp[BUTTON]))

#define TOP_SLIDE_AND_CONSUME IsSlideUp()
#define BOTTOM_SLIDE_AND_CONSUME IsSlideDown()
#define LEFT_SLIDE_AND_CONSUME IsSlideLeft()
#define RIGHT_SLIDE_AND_CONSUME IsSlideRight()

#define TOP_TAP_AND_CONSUME IsTapUp()
#define BOTTOM_TAP_AND_CONSUME IsTapDown()
#define LEFT_TAP_AND_CONSUME IsTapLeft()
#define RIGHT_TAP_AND_CONSUME IsTapRight()
```

**Comment by jonathan46000** [comment]
And by implemented I mean that there is code that already supports that hardware functionality that the event will be based on. 

Jonathan Lundquist

**Comment by jonathan46000** [comment]
I think I said this via email earlier but we have a total of 64K of ram on the chip, 4 major event categories each with several subtypes, and we should try to use less than or close to 1% of ram on the event system.  For everywhere else that we reduce the amount of ram being used we can add that to our budget.  That being said that gives us some constraints to work with on variables actively being stored in memory. We had quite a bit of left over space in program memory and flash last year but I don't want to count on that for this year so as always lets keep it lean, clean, and developer friendly.  With the ram constraint we should build it out such that it's as optimized as it can be and make it so that it's easy to scale down if we have to.  On the flip side of that, if this is written and organized well user applications should be using less ram to store duplicate information(I saw a lot of that in last years code).

**Comment by Matt5sean3** [comment]
So constrain RAM usage to below 640 bytes? Naturally, using even less would be preferable.

What were the event categories?

When you say _event_ in context of the 2016 code, there doesn't appear to have been a proper event system. Are you talking about variables that would get set by interrupts that running code would then check?

**Comment by jonathan46000** [comment]
So what ELI wrote above is essentially most of what people chose to use
last year.  Other system events that occur include the 5 timers, USB
events, and the IR stuff.  This does provide us with 4 distinct categories
of event, each with their own unique elements.  That being said lets
rethink our event system layout with that in mind.  Also the badge has 64KB
of ram total so I'd prefer not to have a 100 of anything if we can help
it.  The event system should be less than 1% of that so lets say we have
~500Bytes(give or take 100) to work with max.  We had an extra 25-30% of
flash/program memory last year so we are good on that front.  Also Eli, the
compression code could be critical this year.  If we optimize memory in
other parts of the code we can add it to our budget.

**Comment by jonathan46000** [comment]
IR, USB, Timers, Touch/D-Pad events so yes, stuff set by interrupts. 

Jonathan Lundquist

**Comment by dotblank** [comment]
There are some button states and touchpad states that look polled. So its not completely ISR driven

**Comment by jonathan46000** [comment]
It's not entirely ISR driven but that doesn't matter much.  The important things is that we can categorize registered events into 4-5 categories and return handlers to a structure that allows access to the data, if an event in that category is fired.

**Comment by Matt5sean3** [comment]
Picking this topic back up, it sounds like the decision is to use an event system with event categories that events are registered to those categories. This seems fine as a hybridization of the two options.

The topic of making writing apps simpler should be revisited. The issue that we'll probably brush up against is that, while C is a fundamentally simple language, fully understanding its usage is a challenge. Can a strong grasp of the full extent of C, particularly including pointers and function pointers, by the app writers be assumed? Without that assumption we'll need to hide those details from the app writers somehow (macros?).

One idea that I had mentioned in person that I'd like to put up for consideration here too is the use of a closure system for managing registered events and ensuring that when the closure is exited any registered callbacks will get cleaned up. This would allow registration of events without worrying that those events won't be deregistered or that other clean-up actions won't get run.

**Comment by jonathan46000** [comment]
In the past we could rely on developer understanding of C, but I think one of our goals is to lower the barrier to entry.  Like you said we could make use of macros to abstract some of this away.  Also I'd like to have some kind of closure system as well.  I don't want to depend on the developer to deregister events.

**Comment by jonathan46000** [comment]
Okay, to rethink this, the real problem trying to be solved here is a very rudimentary method of scheduling, and moving all of the globals to one easy to access location/interface.  Also an API that allows a background app to push data to the menus needs to be implemented.  These are the specific problems that get app code out of system code, and this is what the event system was meant to do in the first place, so these are the goals we need to maintain going forward.

**Comment by Matt5sean3** [comment]
The idea of a comprehensive event system as considered here was rejected at the meeting in favor of continued use of globals to detect that such events have happened. Unfortunately, this has frozen any further conversation about solving the problems the event system would have solved.

In the interest of thawing progress toward those goals, I'm closing this issue and opening new issues ones with the same assignees. Notably, check out issues #13 and #14. If I've missed any goals that the event system was meant to solve, please add additional issues and make a comment here.
