### ISSUE TITLE
Exit app and re-enter or enter app and stay?

### ISSUE THREAD

**Issue by Matt5sean3** [HackRVA/Badge2017-docs#3]
I was going to mention this as part of #2  thread but this goes beyond the scope of the event system and into the wider framework.

Simply, would it be preferable to have an app run its function and stay in that function until it exits or would it be preferable to have an app run its function, exit and re-enter?

in essence:
Stay in the function

```
void my_app() {
  int exit;
  for(exit = 0; !exit; ) {
    /* App does things */
    /* Framework handles events and such in this function */
    yield_to_framework();
  }
}
```

vs.
exit and re-enter

```
/* Interface is designed to run this repeatedly until non-zero is returned */
int my_app() {
  int exit = 0;
  /* App does things */
  return exit;
}
/* Framework handles events and such between the app returning and re-entering */
```

The 2016 code seems to go with exit and re-enter but there are reasonable arguments to be made for staying in the function.

**Comment by jonathan46000** [comment]
There is so much stuff that happens outside the app at this point that I don't think it's worth it to overhaul this aspect.  That being said, I don't want to completely dismiss the idea either.  This is something we should defer to the meeting and ask Paul and Morgan.  Right now USB, some IR, the display, and some other random snippets of code are done in the outer loop.

**Comment by Matt5sean3** [comment]
Personally, I would prefer to change this to "stay in the function", as "exit and re-enter" could be trivially implemented inside of "stay in the function" but "stay in the function" cannot be wisely implemented within "exit and re-enter." It would be a clear increase in flexibility.

Another benefit is that function local stack allocated variables could be used for more variables within the app, decreasing the memory footprint of apps that are not currently in use. This would provide a limited form of dynamic memory without exposing the dangers of malloc. Granted, a person would need to be careful with this as stack memory is very limited at 1kB by default, though if I'm reading the documentation right that can be expanded by use of compiler commands.

This also makes the closure concept I described in the other thread both more useful and easier to implement.

I do agree that we should hear from Paul and Morgan as to what they need on their end and that this would represent a very fundamental change to the design of the badge code.

**Comment by Matt5sean3** [comment]
As it turns out, reorganizing the code to support both types wasn't that difficult. Both the traditional method and the new method are supported in the badge code.
